### PR TITLE
tmplock must be closed before removal

### PR DESCRIPTION
**Pull request by oliverpool**
*From https://github.com/tus/tusd/pull/117*

Quite dirty because I based my modification on the tag `v1.0.0` (and added the tests from master, while disabling the non relevant ones)

### CODE REVIEW

**Comment by Acconut** [comment]
Thank you again for this PR. I actually made the necessary changes to the master branch so we can use it for tusd (and get all updates from @nightlyone's original repository). And there I noticed that this problem should already be addressed: https://github.com/Acconut/lockfile/blob/0a9809d62f141721dc3cd5819f7c708c9d3eaa09/lockfile.go#L101-L105

**Comment by Acconut** [comment]
I also want to look into how we can possible merge this fork back by adding a setting to the TryLock function. Maintaining a fork is not the best solution.

**Comment by oliverpool** [comment]
> by adding a setting to the TryLock function

I think you could add an unexported boolean to the `Lockfile` structure `preventOwnerReLock` (which by default will be false) and a `NewWithoutOwnerReLock` function to initialize it.

**Comment by Acconut** [comment]
I thought about that, too, but Lockfile is not a structure, it's just an alias for a string (see https://github.com/nightlyone/lockfile/blob/master/lockfile.go#L19). This makes your solution sadly not possible without breaking backwards-compatibility.

**Comment by oliverpool** [comment]
I thought that something like that might work: https://play.golang.org/p/PXRr9hsVff, but no...

Other possibility: add a `PreventOwnerReLock` global variable which can be set to true globally.

**Pull request closed without merging**
